test:
  stage: test
  image: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  allow_failure: true
  services:
    - docker:stable-dind
  allow_failure: true
  script:
    - pip install -r requirements.txt
    - pip install pylint pylint-junit
    - pylint --output-format=pylint_junit.JUnitReporter main.py | tee rspec.xml
  artifacts:
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
    when: always